language: python
python:
    - "2.6"
    - "2.7"
install: "pip install -r requirements.txt"
script: nosetests
env:
  global:
  - secure: VgCCQBXI1R86TuyE+0bbFOwncVnIfmvf9FnB3buOgiohHf8NBlwyHVeFDVmop3WzP8KM6udtSns3Krqf2gQNBhwpoA51Udm4nkIGUJSDgTiC6Co9aS6dIny+SYGDI1tGhj35drSsJHcKLJyMik8n3AqBVa7xcJpsSJPdLnVzuaA=
  - secure: jMRXXlviUxskCbrOnCwaDXEG7pY6GwnPbYxe5pfj6bN2R4lrCtdddXK11uWDMl7zrwBo+CL+JuYgJy4uSDxN4qys/MnAbnmluhKHpMpgEOmWeJ20jbyjbi7onvYZNX42VKyP0j+efMdRhSlkjVF9nyZ7HS/kLF3ppFhujRKJWjI=
