language: python
python:
  - "2.6"
  - "2.7"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - pip install -r requirements.txt
script: nosetests
env:
  global:
    SAUCE_USERNAME=saucelabs-python
    secure: "3LdxBHClyN5Cjeq9lZR2ybcCOonZEMzhzU1N56ASwrmi5eQ3FT9DTkp+BznbBmSO7YgtyHPWkp7l3zn8EcJnqQmXTLETFW7pqmePpjbLMVYeGkbcWRhNtytD+FeVcqaiHVYstK9rvCm36ryfc5Vn9yaLvlWcCCkuG3lN1Amnw0M="
addons:
  sauce_connect: true
